language: go
dist: trusty
go:
  - 1.11
os:
  - linux
stages:
  - name: deploy
    if: branch = master
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
script:
  - hugo
install:
  - echo $SSH_PUBLIC_KEY >> $HOME/.ssh/known_hosts
  - sudo apt-get update -y
  - sudo apt-get install -y rsync
  - go get github.com/gohugoio/hugo
