baseURL = "https://giovanis.me/" # Controls base URL
languageCode = "en-us" # Controls site language
title = "giovanism" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating

theme = [
  "fractal-forest",
  "after-dark"
]

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-159117526-1" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
# sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

[params]
  description = "simple, handy, and convenient" # Suggested, controls default description meta
  author = "giovanism" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = true # Optional, set false to disable credits
  images = [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/ASR-33_at_CHM.agr.jpg/800px-ASR-33_at_CHM.agr.jpg"
  ] # Suggested, controls default Open Graph images
  theme_variant = "" # Optional, for use to overriding default theme

[params.layout]

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Homepage"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About me"
    url = "/about/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
